version: "3.7"

services:
  otter-mysql.huanjutang.com:
    image: mysql:5.7.28
    container_name: otter-mysql.huanjutang.com
    volumes:
      - ./my.cnf:/etc/my.cnf:rw
    working_dir: /var/lib/mysql
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456.
    ports:
      - "3306:3306"
    cap_add:
      - SYS_PTRACE